### PR TITLE
Add Replicate demo and API

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @pesser ! 👋 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can run your model! View it here: https://replicate.com/pesser/stable-diffusion

Replicate also have an API, so people can easily run your model from their code:

```
import replicate
model = replicate.models.get("pesser/stable-diffusion")
model.predict(prompt="a virus monster is playing guitar, oil on canvas")
```

[Claim your page here](https://replicate.com/pesser/stable-diffusion/claim) so you can edit it, and we'll feature it on our website and tweet about it too.

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by neverix** [comment]
This leaks the text2img model checkpoint

**Comment by chenxwh** [comment]
> This leaks the text2img model checkpoint

? the checkpoint is publicly available from the repo

**Comment by neverix** [comment]
> ? the checkpoint is publicly available from the repo

I'm not sure what you're talking about, all references in the repo link to Stability's internal cluster?

**Comment by chenxwh** [comment]
> > ? the checkpoint is publicly available from the repo
> 
> I'm not sure what you're talking about, all references in the repo link to Stability's internal cluster?

https://github.com/pesser/stable-diffusion#text-to-image

**Comment by neverix** [comment]
That is not Stable Diffusion, it's an older model that has been available since April at https://github.com/CompVis/latent-diffusion

**Comment by chenxwh** [comment]
Aware latent-diffusion. Maybe it should be stated in the readme, similarly someone asked [here](https://github.com/pesser/stable-diffusion/issues/1#issuecomment-1182610546) but still using this way

**Comment by neverix** [comment]
Yes this specific checkpoint is causing a lot of confusion

**Pull request closed without merging**
